server:
  port: 8011
  forward-headers-strategy: native

app:
  kafka:
    topics:
      notification-sse: notification.sse

sse:
  default:
    timeout: 30 #ë¶„

gateway:
  auth:
    value: local-gateway


external:
  base-url:
    core: http://localhost:8082/internal
  auth:
    value: internal-request

internal:
  auth:
    value: internal-notifications

logging:
  level:
    root: info
    com.myce: debug
    com.myce.common.aop.ControllerLoggingAspect: debug

spring:
  profiles:
    active: ${PROFILE:local} # local | product
    include:
      - domain
      - common
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: notification-sse-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.myce.notification.dto.request"
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls: # isActive
            enable: true
  servlet: # file uploads
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    import:
      - optional:file:./.env[.properties]
      - optional:file:../.env[.properties]

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    persistAuthorization: true
  api-docs:
    path: /v3/api-docs
