server:
  port: 8083
  forward-headers-strategy: native

logging:
  level:
    root: info
    com.myce: debug
    com.myce.common.aop.ControllerLoggingAspect: debug

spring:
  profiles:
    active: ${PROFILE:local} # local | product
    include:
      - domain
      - common
  servlet: # file uploads
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config: # load .env variables
    import:
      - optional:file:./.env[.properties]
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    persistAuthorization: true
  api-docs:
    path: /v3/api-docs

app:
  kafka:
    topics:
      notification-sse: notification.sse
